joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1 #vertikal maju mundur
    scale_linear: #kecepatan berjalan
      x: 0.5 #aslinya 0.5
    scale_linear_turbo: #kecepatan penambahan
      x: 1.0 #aslinya 1.0

    axis_angular:
      yaw: 0 #horisontal belok kanan kiri
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0


    enable_button: 0 #X
    enable_turbo_button: 5 #R1

    require_enable_button: true